import styles from './json-compare.module.css'

interface DiffOutputProps {
  diffHtml: string | null
  isIdentical: boolean
  hasBothValid: boolean
}

/**
 * Renders the jsondiffpatch HTML diff output with theme-aware styling.
 * Uses dangerouslySetInnerHTML which is safe here — HTML is generated by
 * jsondiffpatch from parsed JSON data, not from raw user input.
 */
export function DiffOutput({ diffHtml, isIdentical, hasBothValid }: DiffOutputProps) {
  if (!hasBothValid) {
    return (
      <div className={styles.diffPlaceholder}>
        Enter valid JSON in both panels to see diff
      </div>
    )
  }

  if (isIdentical) {
    return (
      <div className={`${styles.diffPlaceholder} ${styles.diffIdentical}`}>
        JSONs are identical
      </div>
    )
  }

  return (
    <div
      className={styles.diffHtml}
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: diffHtml ?? '' }}
    />
  )
}
